---
- name: Copy finder script
  copy:
    src: "log4j-finder"
    dest: "/root/log4j-finder"
    owner: root
    group: root
    mode: "0750"

- name: Run a script finder log4shell
  command: /root/log4j-finder
  register: result

- name: Get path for log4j lib
  set_fact:
    path_log4j: "{{ result.stdout | regex_findall('(?<=VULNERABLE)*(?!\\[1m)[/]\\S*jar', multiline=True, ignorecase=True) }}"
    cacheable: no

- name: Get version log4j lib
  set_fact:
    version_log4j: "{{ result.stdout | regex_findall('(?<=VULNERABLE)*(?<=log4j.)[2].\\d{1,2}.\\d{1,2}.-.[2].\\d{1,2}.\\d{1,2}', multiline=True, ignorecase=True) }}"
    cacheable: no

- debug:
    msg: "{{ item }}"
  loop: "{{ path_log4j }}"

- debug:
    msg: "{{ item }}"
  loop: "{{ version_log4j }}"

- name: Remove JndiLookup.class from the class path
  block:
    - name: Set LOG4J_FORMAT_MSG_NO_LOOKUPS to true
      debug:
          msg: "{{ item }}"
      loop: "{{ version_log4j }}"

  when: ('2.15.0' not in version_log4j)
