---
- name: Copy finder script
  copy:
    src: "log4j-finder.py"
    dest: "/root/log4j-finder.py"
    owner: root
    group: root
    mode: "0750"

- name: Run a script finder log4shell
  script: /root/log4j-finder.py
  args:
    executable: python3
  register: result

- name: Get libs number log4j
  set_fact:
    vulnerable_log4shell: "{{ result.stdout | regex_findall('(?<=VULNERABLE)*(?<=log4j.)[12].\\d{1,2}', multiline=True, ignorecase=True) | unique }}"
    cacheable: no

- debug:
    msg: "ENV {{item}}"
  with_items: "{{ vulnerable_log4shell }}"
  when: "{{item}} != 2.9 and {{item}} > 2.12"

- debug:
    msg: "Manual {{item}}"
  with_items: "{{ vulnerable_log4shell }}"
  when: "{{item}} == 2.9"
