---
- name: Copy finder script
  copy:
    src: "log4j-finder.py"
    dest: "/root/log4j-finder.py"
    owner: root
    group: root
    mode: "0750"

- name: Run a script finder log4shell
  script: /root/log4j-finder.py
  args:
    executable: python3
  register: result

- debug:
    msg: "{{ result.stdout | regex_findall('(?<=VULNERABLE)*(?<=log4j.)[12].\\d{1,2}.\\d{1,2}', multiline=True, ignorecase=True) }}"

