---
- name: Check if lib fixed
  stat: path="/root/log4j-fixed"
  register: log4j_fixed

- meta: end_play
  when: log4j_fixed.stat.exists | bool == true

- name: Copy finder script
  copy:
    src: "log4j-finder"
    dest: "/root/log4j-finder"
    owner: root
    group: root
    mode: "0750"

- name: Run a script finder log4shell
  command: /root/log4j-finder
  changed_when: false
  register: result

- name: Vulnerable log4j
  set_fact:
    vulnerable_log4j: "{{ result.stdout | regex_findall('(?P<VULNERABLE>VULNERABLE)', multiline=True, ignorecase=True) }}"
    cacheable: no

- name: Get path for log4j lib
  set_fact:
    path_log4j: "{{ result.stdout | regex_findall('(?<=VULNERABLE)*(?!\\[1m)[/]\\S*jar', multiline=True, ignorecase=True) }}"
    cacheable: no

- name: Get version log4j lib
  set_fact:
    version_log4j: "{{ result.stdout | regex_findall('(?<=VULNERABLE)*(?<=log4j.)[2].\\d{1,2}.\\d{1,2}.-.[2].\\d{1,2}.\\d{1,2}', multiline=True, ignorecase=True) }}"
    cacheable: no

- name: Set fatc paths and versions log4j lib
  set_fact:
    info_log4j: "{{ info_log4j | default([]) }} + ['PATH: {{ item.0 }} VERSION: {{ item.1 }}']"
    cacheable: no
  loop: "{{ path_log4j | zip(version_log4j) | list }}"

- name: Show paths
  debug:
    msg: "{{ item }}"
  loop: "{{ path_log4j }}"

- name: Show versions
  debug:
    msg: "{{ item }}"
  loop: "{{ version_log4j }}"

- name: Show paths and versions
  debug:
    msg: "{{ item }}"
  loop: "{{ info_log4j }}"
  when: (info_log4j is defined)

- name: Remove JndiLookup.class from the libs
  block:
    - name: Remove class JndiLookup
      command: "zip -q -d {{ item }} org/apache/logging/log4j/core/lookup/JndiLookup.class"
      loop: "{{ path_log4j }}"

    - name: Create file fixed
      file:
        path: /root/log4j-fixed
        state: touch
        mode: u=rw,g=r,o=r
  when: (log4j_fix is defined and log4j_fix | bool == true ) and ('2.15.0' not in version_log4j)

- name: Include task for generate ans send mail report
  include: report.yml
  when: mail_host is defined and (mail_rcpt_to is defined or report_cont_mail is defined)
...
